[package]
name = "lushus-jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
jsonwebtoken = "8"
rand = "0.8"
rsa = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1"
